project_id = "kstfczzkskpmsswmanif"

[functions.db-proxy]
verify_jwt = false

[functions.ai-chat]
verify_jwt = true

[functions.deadline-notifications]
verify_jwt = false

[functions.send-external-notification]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.setup-telegram-webhook]
verify_jwt = false

[functions.sync-protocol-tasks]
verify_jwt = false

[functions.storage-proxy]
verify_jwt = false

[functions.telegram-channel]
verify_jwt = false

[functions.yandex-disk-proxy]
verify_jwt = false

[functions.telegram-image-proxy]
verify_jwt = false

[functions.yandex-s3-upload]
verify_jwt = false

[functions.avatar-proxy]
verify_jwt = false

[functions.send-calendar-invite]
verify_jwt = false
